{
 "title": "Kubernetes / Networking / Cluster",
 "description": "prometheus operator ",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "4h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 }, "options": { "content": "12157" } },
  {
   "title": "Current Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Rate of Bytes Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Current Rate of Bytes Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Current Status",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      },
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Rate of Bytes Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Average Rate of Bytes Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of TCP Retransmits out of all sent segments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(node_netstat_Tcp_RetransSegs[$interval:$resolution]) / rate(node_netstat_Tcp_OutSegs[$interval:$resolution])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of TCP SYN Retransmits out of all retransmits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(node_netstat_TcpExt_TCPSynRetrans[$interval:$resolution]) / rate(node_netstat_Tcp_RetransSegs[$interval:$resolution])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}