{
 "title": "Network checker",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Global availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "Total" },
    {
     "expr": "sum(ncagent_http_probe_connection_result)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Per node availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ncagent_http_probe_connection_result) by (agent)",
     "legendFormat": "{{ agent }}"
    }
   ]
  },
  {
   "title": "Latency per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ncagent_http_probe_connect_time_ms) by (agent)",
     "legendFormat": "{{ agent }}"
    }
   ]
  },
  {
   "title": "Kubernetes node status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}