#!/usr/bin/env bash

# DESTINATION VARIABLESTINATION VARIABLES
export token=eyJrIjoic284UzJ4Qkx5MkdJUWxKVzBYcnQyZm9aajhEcFlhbGUiLCJuIjoiYXBpX2tleSIsImlkIjoxfQ==
export grafanaurl=http://172.17.0.1:3000/api

cd dashboards/sai

for FILE in *dashboard*; do
  echo Importing Dashboard: $FILE
  cat $FILE | jq '. * {overwrite: true, dashboard: {id: null}}' | curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $token" "$grafanaurl/dashboards/db" -d @- ;
done



# https://www.ifconfig.it/hugo/2021/12/backup-grafana-dashboards-with-api-and-jq/
# https://gist.github.com/crisidev/bd52bdcc7f029be2f295
