{
 "title": "GCE VM Instance Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   },
   { "name": "vm_instances" }
  ]
 },
 "panels": [
  {
   "title": "GCE VM Instance Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 10 charts for the related [GCE VM metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-compute), including metrics for CPU, disk read/write, and network."
   }
  },
  {
   "title": "GCE VM Instance - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}}",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "s{uptime}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Disk read operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent packets count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/nat/sent_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "{packet}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Received bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}