{
 "title": "syslog messages trimming",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Facility",
    "query": "kernel messages, user-level messages,mail system,system daemons,*security/authorization messages,messages generated internally by Syslog,line printer subsystem, network news subsystem,UUCP subsystem,,clock daemon,security/authorization messages,FTP daemon, NTP subsystem, log audit, log alert, \tclock daemon,local use 0 (local0), local use 1 (local1), local use 2 (local2),local use 3 (local3),local use 4 (local4),local use 5 (local5),\tlocal use 6 (local6),local use 7 (local7)"
   },
   {
    "name": "facilitynames",
    "query": "select facilitynames from logs;"
   },
   {
    "name": "facilitycodes",
    "query": "select facilitycodes from logs where facilitynames = '$facilitynames';"
   },
   {
    "name": "experimental1",
    "query": "select case facilitynames when 'one' then 1 when 'two' then 2 end from logs;"
   },
   { "name": "custom", "query": "one : 1, two : 2" },
   {
    "name": "variableTextValue",
    "query": "SELECT\n    facilitynames AS __text,\n    facilitycodes AS __value\nFROM logs"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>${facilitycodes}</h1>\n<h1>${facilitynames}</h1>\n"
   }
  },
  {
   "title": "custom",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\n${custom}\n\n${variableTextValue}"
   }
  },
  {
   "title": "syslog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actual data",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  numbers, message\nFROM logs\nWHERE\n  information = '10'"
      }
     ]
    },
    {
     "title": "string to array",
     "type": "table",
     "description": "string_to_array takes from which word to which word you need to trim",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  numbers,message, (string_to_array(message, ' '))[1:3] \nFROM logs\nWHERE\n  information = '10'"
      }
     ]
    },
    {
     "title": "using substring",
     "type": "table",
     "description": "substr takes 3 arguments (column, start substring from, how long the substring should be)",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  numbers, message, SUBSTR(message,3,5)\nFROM logs\nWHERE\n  information = '10'"
      }
     ]
    }
   ]
  }
 ]
}