{
 "title": "Grafana",
 "tags": [ "ApplicationMonitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 1, "w": 19, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  {
   "title": "Members In Grafana",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "grafana_stat_totals_admins{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Admins"
    },
    {
     "expr": "grafana_stat_totals_editors{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Editors"
    },
    {
     "expr": "grafana_stat_totals_viewers{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Members In Grafana",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_admins{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Admins"
    },
    {
     "expr": "grafana_stat_totals_editors{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Editors"
    },
    {
     "expr": "grafana_stat_totals_viewers{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Folders"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_access_user_count{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Total Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_library_panels{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Library Panels"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Organization Count"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_playlists{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "PlayList Count"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "grafana_stat_totals_datasource{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "piechart",
   "description": " User that have been logged in sometime during the last 30 days",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_active_admins{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Admins"
    },
    {
     "expr": "grafana_stat_totals_active_editors",
     "legendFormat": "Editors"
    },
    {
     "expr": "grafana_stat_totals_active_viewers{instance=\"localhost:3000\"\n, job=\"grafana\"}",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "About Grafana",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "grafana_build_info{instance=\"localhost:3000\", job=\"grafana\"} - 0"
    }
   ]
  },
  {
   "title": "Grafana Alerts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 14 },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard", "legendFormat": "Dashboards" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_access_team_count{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Teams Count"
    }
   ]
  },
  {
   "title": "Grafana Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_build_info{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "No.of O.S Threads created",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "go_threads{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Grafana Alerts",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "External Plugins",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 24 },
   "targets": [
    { "expr": "grafana_plugin_build_info" }
   ]
  },
  {
   "title": "External Plugins",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_plugin_build_info", "legendFormat": "{{plugin_id}} - {{version}}" }
   ]
  },
  {
   "title": "Grafana Visualizations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 15 },
     "targets": [
      { "expr": "time()" }
     ]
    },
    {
     "title": "Dashboards",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 17 },
     "targets": [
      { "expr": "grafana_stat_totals_dashboard", "legendFormat": "Dashboards" }
     ]
    },
    {
     "title": "Annotations",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_stat_totals_annotations"
      }
     ]
    },
    {
     "title": "Folders in Grafana",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "grafana_stat_totals_folder", "legendFormat": "Folders" }
     ]
    },
    {
     "title": "Total Users",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "grafana_access_user_count{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "Users"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "piechart",
     "description": " User that have been logged in sometime during the last 30 days",
     "gridPos": { "h": 6, "w": 8, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_stat_totals_active_admins{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "Admins"
      },
      {
       "expr": "grafana_stat_totals_active_editors",
       "legendFormat": "Editors"
      },
      {
       "expr": "grafana_stat_totals_active_viewers{instance=\"localhost:3000\"\n, job=\"grafana\"}",
       "legendFormat": "Viewers"
      }
     ]
    },
    {
     "title": "Organization Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "grafana_stat_total_orgs" }
     ]
    }
   ]
  },
  {
   "title": "View-1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Members In Grafana",
     "type": "table",
     "gridPos": { "h": 4, "w": 15, "x": 0, "y": 21 },
     "targets": [
      { "expr": "grafana_access_team_count", "legendFormat": "Teams" },
      {
       "expr": "grafana_stat_totals_admins{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "Admins"
      },
      {
       "expr": "grafana_stat_totals_editors{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "Editors"
      },
      {
       "expr": "grafana_stat_totals_viewers{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "Viewers"
      }
     ]
    },
    {
     "title": "Dashboards Count",
     "type": "gauge",
     "description": "Gives the number of dashboards present",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "grafana_stat_totals_dashboard" }
     ]
    },
    {
     "title": "Users Count",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "grafana_stat_total_users" }
     ]
    },
    {
     "title": "Grafana performance",
     "type": "timeseries",
     "description": "Aggregated over all Grafana nodes.",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{job=\"grafana\"})",
       "legendFormat": "go routines",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
       "legendFormat": "memory usage"
      }
     ]
    },
    {
     "title": "Playlist Count",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_stat_total_playlists{instance=\"localhost:3000\", job=\"grafana\"}"
      }
     ]
    },
    {
     "title": "Active Instances",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"grafana\"}"
      }
     ]
    },
    {
     "title": "Library Panels",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_stat_totals_library_panels{instance=\"localhost:3000\", job=\"grafana\"}"
      }
     ]
    },
    {
     "title": "Data Sources",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "grafana_stat_totals_datasource{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "{{plugin_id}}"
      }
     ]
    },
    {
     "title": "Grafana Version",
     "type": "table",
     "gridPos": { "h": 4, "w": 15, "x": 9, "y": 30 },
     "targets": [
      {
       "expr": "grafana_build_info{instance=\"localhost:3000\", job=\"grafana\"}",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  }
 ]
}