{
 "title": "Memory",
 "tags": [ "ServerMonitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$serverName\"},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "serverName",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">${serverName}</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "time()" }
   ]
  },
  {
   "title": "Memory Stat",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$Server\", job=\"$job\"}-\nnode_memory_SwapFree_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "gauge",
   "description": "By dividing the available bytes with total bytes will give you the memory availability",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"}\n / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "gauge",
   "description": "Gives the total RAM given to the machine",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM TOTAL"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "By removing the free memory + cached memory + buffer memory from the total memory will give you the used RAM",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "RAM Cache+Buffer",
   "type": "gauge",
   "description": "Cache : Fastest Memory that contains mostly used data\nBuffer : memory that carries the data from one place to another",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "SWAP is a memory used when RAM Exceeds",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\", instance=\"$Server\"}-\nnode_memory_SwapFree_bytes{job=\"$job\", instance=\"$Server\"}",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Stat (old)",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\", job=\"$job\"}-\nnode_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Stat",
   "type": "timeseries",
   "description": "Information about Total, Used , cache + buffer and free Memory",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\", job=\"$job\"}-\nnode_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "gauge",
   "description": "Gives the Amount of Free RAM given to the system",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Available (%)",
   "type": "timeseries",
   "description": "Amount of memory available to the system",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"}\n / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100",
     "legendFormat": "Memory Available"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "diving the available bytes with total bytes gives the availability percentage. by removing outcome with 100 gives the memory utilization",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - \n(node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100)"
    }
   ]
  },
  {
   "title": "experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Statistics",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes[$__rate_interval])"
      },
      { "expr": "node_memory_MemFree_bytes" },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes[$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_Buffers_bytes [$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_Cached_bytes [$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_Active_bytes [$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_SwapCached_bytes[$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_SwapTotal_bytes[$__rate_interval])"
      },
      {
       "expr": "avg_over_time(node_memory_SwapFree_bytes[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Shared Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Shmem_bytes{instance=\"DevServer:9100\", job=\"node\"}",
       "legendFormat": "Shared"
      }
     ]
    }
   ]
  }
 ]
}