{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "experiment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node\", instance=\"localhost:9100\"} != 0"
    },
    { "expr": "memory_utilized", "legendFormat": "Memory" },
    {
     "expr": "instance:node_cpu_utilisation:rate5m{instance=\"DevServer:9100\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 } },
  {
   "title": "customized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "memory_utilized", "legendFormat": "A" },
    {
     "expr": "100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "B"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Utilzation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - \n(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "General Query",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"DevServer:9100\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "cpu utilizaiton (custom)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_utilized{instance=\"DevServer:9100\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization General",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * node_memory_MemFree_bytes{instance=\"DevServer:9100\", job=\"node\"} / node_memory_MemTotal_bytes{instance=\"DevServer:9100\", job=\"node\"})"
    }
   ]
  },
  {
   "title": "Memory Utilized (custom query)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_utilized{instance=\"DevServer:9100\", job=\"node\"}"
    }
   ]
  }
 ]
}