{
 "title": "Application Monitoring",
 "tags": [ "application" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Members in grafana",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grafana_access_team_count{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Teams"
    },
    {
     "expr": "grafana_access_user_count{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "grafana_stat_totals_admins{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Admins"
    },
    {
     "expr": "grafana_stat_totals_editors{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Editors"
    },
    {
     "expr": "grafana_stat_totals_viewers{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Grafana Active Instances",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Dashboards Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=\"localhost:3000\", job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "User count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_stat_total_users" }
   ]
  },
  {
   "title": "Playlist count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_playlists{instance=\"localhost:3000\", job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Library panels",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_library_panels{instance=\"localhost:3000\", job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_datasource{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "targets": [
    { "expr": "grafana_build_info" }
   ]
  }
 ]
}