{
 "title": "Memory",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   { "name": "job", "query": "node, node1, node2, node3" }
  ]
 },
 "panels": [
  {
   "title": "Memory Available",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"}\n / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - \n(node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100)"
    }
   ]
  },
  {
   "title": "Total Ram",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM TOTAL"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "RAM cache+Buffer",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "SWAP used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\", instance=\"$Server\"}-\nnode_memory_SwapFree_bytes{job=\"$job\", instance=\"$Server\"}",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Stat",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\", job=\"$job\"}-\nnode_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Stat",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} - \nnode_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"} - \n(node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$Server\", job=\"$job\"} + \nnode_memory_Buffers_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM cache+Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\", job=\"$job\"}-\nnode_memory_SwapFree_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "SWAP used"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"}\n / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100",
     "legendFormat": "Memory Available"
    }
   ]
  }
 ]
}