{
 "title": "Server Monitoring",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$Server\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "CPU - System Mode($interval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU - User Mode($interval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU - IO Wait Mode ($interval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"iowait\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "CPU - Idle Mode($interval)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Modes ($interval)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\".*irq\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU - Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system', instance=\"$Server\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Utilzation($interval)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "CPU Modes ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"system\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"user\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\".*irq\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(avg by (mode) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage, Memory Usage, Disk Usage ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "CPU "
    },
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"$Server\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$Server\", job=\"$job\"} * 100)",
     "legendFormat": "Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"} * 100) /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "CPU Usage ($interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$Server\", job=\"$job\"}[$interval])) * 100)",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "cpu -load1m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load1m"
    }
   ]
  },
  {
   "title": "cpu -load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load5"
    }
   ]
  },
  {
   "title": "Load15m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "Load15m"
    }
   ]
  },
  {
   "title": "cpu -load1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load1m"
    }
   ]
  },
  {
   "title": "cpu -load5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load5"
    }
   ]
  },
  {
   "title": "Load15m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "Load15m"
    }
   ]
  },
  {
   "title": "cpu -load1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load1m"
    }
   ]
  },
  {
   "title": "cpu -load5",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "cpu -load5"
    }
   ]
  },
  {
   "title": "Load15m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "Load15m"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$Server\",job=\"$job\",mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{instance=\"$Server\" , job=\"$job\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$Server\",job=\"$job\",mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  }
 ]
}