{
 "title": "cpu in table",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server1"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server10"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server2"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server3"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server4"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server5"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server6"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server7"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server8"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server9"
    }
   ]
  },
  {
   "title": "CPU Utilization (all same) ",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 01"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 02"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 03"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 04"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 05"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\", job=\"node\"}[2m])) * 100)",
     "legendFormat": "Server 06"
    }
   ]
  },
  {
   "title": "application Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\", instance=\"localhost:9100\", job=\"node\", mode=\"idle\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "node_cpu_seconds_total{cpu=\"1\", instance=\"localhost:9100\", job=\"node\", mode=\"idle\"}",
     "legendFormat": "Server02"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=\"localhost:9100\", mode=\"idle\", cpu=\"0\"}",
     "legendFormat": "cpu-0"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "up{instance=\"localhost:3000\", job=\"grafana\"}",
     "legendFormat": "grafana"
    },
    {
     "expr": "up{instance=\"localhost:9090\", job=\"prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  }
 ]
}