{
 "title": "nodes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "group left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up * on(instance) group_left(sysname) (node_uname_info)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (device) (\n    node_filesystem_size_bytes{job=\"node\", fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{job=\"node\", fstype!=\"\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "network received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\", device!=\"lo\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum without (mode, cpu)(rate(node_cpu_seconds_total[1m]))"
    }
   ]
  }
 ]
}