{
 "title": "syslogMainExtended",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "DevServer:9100, DevServer:9200" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "reduce(mode=series to rows); cal=max; enabled labels to fields",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\", mode=\"idle\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "reduce(mode=series to rows); cal=max; enabled labels to fields",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)"
    },
    {
     "expr": "node_load5{job=~\"$job\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[2m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)"
    },
    {
     "expr": "node_load5{job=~\"$job\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[2m])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[2m])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[2m])*8) by (instance)"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "reduce(mode=series to rows); cal=max; enabled labels to fields",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "series to rows",
   "type": "table",
   "description": "requires two queries, convert into table of one",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "up{job=\"grafana\"} - 0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"prometheus\"} - 0",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}