{
 "title": "Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Current Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nginx_active_connections)" }
   ]
  },
  {
   "title": "Least CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu{mode=\"idle\"}[1m])) by (instance)))"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_avail{mountpoint!~\".*(serviceaccount|proc|sys).*\"}/node_filesystem_size{mountpoint!~\".*(serviceaccount|proc|sys).*\"})"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable/node_memory_MemTotal)"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(http_request_duration_seconds_count{status_code=\"200\", method=\"GET\"}[10m]))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts[15m]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree + node_memory_Buffers + node_memory_Cached",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu{mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(node_filesystem_avail{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}/node_filesystem_size{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}) by (device, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(node_disk_io_time_ms[1m])", "legendFormat": "{{instance}} {{device}}" }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "TOP 7 CPU Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube:cpu:top7", "legendFormat": "{{pod_name}}" }
   ]
  }
 ]
}