{
 "title": "Disk",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk space utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"} * 100)\n /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$Server\", job=\"$job\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free Space for Each partiton",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs', mountpoint=\"/\"}",
     "legendFormat": "A"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "B%"
    }
   ]
  },
  {
   "title": "File system Space Available",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$Server\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  }
 ]
}