{
 "title": "GKE Prometheus Pod/Node Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GKE Prometheus Pod/Node Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has example charts for metrics exported by Prometheus, for example metrics from [Kubernetes pod metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md)"
   }
  },
  {
   "title": "kube_pod_status_phase [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.phase" ],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_pod_status_phase",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "kube_pod_status_ready [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.namespace" ],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_pod_status_ready",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "kube_pod_container_status_running [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.namespace" ],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_pod_container_status_running",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "kube_node_status_condition [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.condition" ],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_condition",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "kube_node_status_capacity_pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_capacity_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "kube_node_status_allocatable_pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/prometheus/kube_node_status_allocatable_pods",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  }
 ]
}