{
 "title": "Prometheus Network Exporter",
 "description": "Prometheus Network Exporter",
 "tags": [
  "linux",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source:", "query": "prometheus" },
   { "name": "g_ports", "label": "Gateway:", "query": "eth0, eth1, eth2, eth3" },
   {
    "name": "s_ports",
    "label": "Switch:",
    "query": "0/1, 0/2, 0/3, 0/4, 0/5, 0/6, 0/7, 0/8, 0/9, 0/10, 0/11, 0/12, 0/13, 0/14, 0/15, 0/16, 0/17, 0/18"
   },
   { "name": "gateway", "label": "Gateway IP", "query": "10.10.1.1" },
   { "name": "switch1", "label": "Switch 1 IP", "query": "10.10.1.11" },
   { "name": "w_radio", "label": "WiFi:", "query": "rai1, rai2" },
   { "name": "unifiap1", "label": "Unifi AP 1 IP", "query": "10.10.1.21" }
  ]
 },
 "panels": [
  { "title": "Gateway: $g_ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "g_ports" },
  {
   "title": "Tx (Recent)",
   "type": "stat",
   "description": "The total number of octets transmitted out of the interface per second, including framing characters",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Recent)",
   "type": "stat",
   "description": "The total number of octets received on the interface per second, including framing characters",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Total)",
   "type": "stat",
   "description": "The total number of octets transmitted out of the interface, including framing characters, in the given timespan",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Total)",
   "type": "stat",
   "description": "The total number of octets received on the interface, including framing characters, in the given timespan",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Transmit / Receive",
   "type": "timeseries",
   "description": "The total number of octets transmitted out of and received on the interface per second, including framing characters",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[5m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$gateway\",ifName=\"$g_ports\"}[5m])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Adm. Status",
   "type": "stat",
   "description": "The desired state of the interface ",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The time (sysUpTime) since the network management portion of the system was last re-initialized",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$gateway\"}/100"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "description": "The difference from sysUpTime at the time the interface entered its current operational state",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sysUpTime{instance=\"$gateway\"} - on(instance) ifLastChange{instance=\"$gateway\",ifName=\"$g_ports\"}) / 100"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "stat",
   "description": "The current operational state of the interface",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "description": "An estimate of the interface's current bandwidth",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  {
   "title": "Maximum TU",
   "type": "stat",
   "description": "The size of the largest packet which can be sent/received on the interface",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$gateway\",ifName=\"$g_ports\"}"
    }
   ]
  },
  { "title": "WiFi: $w_radio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "w_radio" },
  {
   "title": "Tx (Recent)",
   "type": "stat",
   "description": "The total number of octets transmitted out of the interface per second, including framing characters",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Recent)",
   "type": "stat",
   "description": "The total number of octets received on the interface per second, including framing characters",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Total)",
   "type": "stat",
   "description": "The total number of octets transmitted out of the interface, including framing characters, in the given timespan",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Total)",
   "type": "stat",
   "description": "The total number of octets received on the interface, including framing characters, in the given timespan",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=\"$unifiap1\",ifName=\"$w_radio\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Drop Rate)",
   "type": "stat",
   "description": "The ratio (percentage) of outbound packets which were chosen to be discarded or contained errors, in the given timespan",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(unifiVapTxDropped{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) + delta(unifiVapTxErrors{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range])) / delta(unifiVapTxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Rx (Drop Rate)",
   "type": "stat",
   "description": "The ratio (percentage) of inbound packets which were chosen to be discarded or contained errors, in the given timespan",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(unifiVapRxDropped{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) + delta(unifiVapRxErrors{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range])) / delta(unifiVapRxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Tx (Retry Rate)",
   "type": "stat",
   "description": "The ratio (percentage) of outbound packets that were transmitted with retries, in the given timespan",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(delta(unifiVapTxRetries{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) / delta(unifiVapTxPackets{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}[$__range]) * 100, 0)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Adm. Status",
   "type": "stat",
   "description": "The desired state of the interface ",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The time (sysUpTime) since the network management portion of the system was last re-initialized",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$unifiap1\"}/100"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "description": "The difference from sysUpTime at the time the interface entered its current operational state",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sysUpTime{instance=\"$unifiap1\"} - on(instance) ifLastChange{instance=\"$unifiap1\",ifName=\"$w_radio\"}) / 100"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "stat",
   "description": "The current operational state of the interface",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "WiFi Channel",
   "type": "stat",
   "description": "The current channel of the wireless network on this interface",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifiVapChannel{instance=\"$unifiap1\",unifiVapName=\"$w_radio\"}"
    }
   ]
  },
  {
   "title": "Maximum TU",
   "type": "stat",
   "description": "The size of the largest packet which can be sent/received on the interface",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$unifiap1\",ifName=\"$w_radio\"}"
    }
   ]
  },
  { "title": "Switch Stats (Port Tx/Rx)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Transmit / Receive (Port 1-9)",
   "type": "table",
   "description": "The total number of octets transmitted out of and received on the interface - per second and in the given timespan",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$switch1\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$switch1\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{instance=\"$switch1\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{instance=\"$switch1\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{instance=\"$switch1\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Transmit / Receive (Port 10-18)",
   "type": "table",
   "description": "The total number of octets transmitted out of and received on the interface - per second and in the given timespan",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$switch1\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$switch1\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{instance=\"$switch1\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{instance=\"$switch1\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{instance=\"$switch1\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  { "title": "Switch Stats (Packet types)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Tx Unicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Broadcast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Multicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Unicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Broadcast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutBroadcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Tx Multicast Packets",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, and which were addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Unicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Broadcast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Multicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Unicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast or broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Broadcast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a broadcast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInBroadcastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  },
  {
   "title": "Rx Multicast Packets",
   "type": "timeseries",
   "description": "The number of packets, delivered by this sub-layer to a higher (sub-)layer, which were not addressed to a multicast address at this sub-layer",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInMulticastPkts{instance=\"$switch1\"}[$__range])",
     "legendFormat": "{{ifAlias}}"
    }
   ]
  }
 ]
}